CREATE TABLE ALL_TYPES(
ID      NUMBER(5) PRIMARY KEY,
C_SMALLINT         SMALLINT,
C_INTEGER            INTEGER,
C_REAL           REAL,
C_DOUBLE         DOUBLE PRECISION,
C_BIGDECIMAL     DECIMAL(13,0),
C_VARCHAR2         VARCHAR2(254),
C_NVARCHAR2         NVARCHAR2(254),
C_VARCHAR        VARCHAR(254),
C_CHAR        CHAR(254),
C_NCHAR        NCHAR(254),
C_NUMBER       NUMBER(3,2),
C_LONG          LONG,
C_RAW           RAW(2000),
C_INTERVAL_Y_M INTERVAL YEAR (3) TO MONTH,
C_INTERVAL_D_S INTERVAL DAY (3) TO SECOND,
C_DATE       DATE,
C_CLOB            CLOB,
C_BLOB            BLOB,
C_BFILE           BFILE
)


CREATE TABLE PARENT_TABLE (
         ID      NUMBER(5) PRIMARY KEY,
         NAME      VARCHAR2(50) NOT NULL
)


CREATE TABLE CHILD_TABLE (
         ID      NUMBER(5) PRIMARY KEY,
		 PARENT_ID NUMBER(5) CONSTRAINT FK_CHILD_TABLE_PARENT_TABLE REFERENCES PARENT_TABLE (ID),
         NAME      VARCHAR2(50) NOT NULL
)


CREATE VIEW PARENT_CHILD_VIEW AS 
   SELECT P.ID AS PARENT_ID, P.NAME AS PARENT_NAME, C.ID AS CHILD_ID, C.NAME AS CHILD_NAME
   FROM CHILD_TABLE C LEFT JOIN PARENT_TABLE P ON C.PARENT_ID = P.ID
